# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('picture', models.CharField(default='', max_length=255)),
                ('hexDominantColor', models.CharField(default='', max_length=255)),
                ('hexBackgroundColor', models.CharField(default='', max_length=255)),
                ('hexAccentColor', models.CharField(default='', max_length=255)),
                ('rgbDominantColor', models.CharField(default='', max_length=255)),
                ('rgbBackgroundColor', models.CharField(default='', max_length=255)),
                ('rgbAccentColor', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('emotion', models.CharField(default='Happy', max_length=255)),
            ],
        ),
    ]
