# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cap',
            fields=[
                ('name', models.CharField(default='', max_length=255)),
                ('SKU', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=255)),
                ('audience', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
                ('price', models.CharField(default='', max_length=255)),
                ('detail', models.CharField(default='', max_length=255)),
                ('team', models.CharField(default='', max_length=255)),
                ('png', models.ImageField(blank=True, null=True, upload_to='pngs/')),
            ],
        ),
        migrations.CreateModel(
            name='HEX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant', models.CharField(default='', max_length=255)),
                ('background', models.CharField(default='', max_length=255)),
                ('accent', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RGB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant', models.CharField(default='', max_length=255)),
                ('background', models.CharField(default='', max_length=255)),
                ('accent', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cap',
            name='hex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cappr.HEX'),
        ),
        migrations.AddField(
            model_name='cap',
            name='rgb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cappr.RGB'),
        ),
    ]
